### ISSUE TITLE
The plugin wont start :(

### ISSUE THREAD

**Issue by ExplodingCraftPE** [BuycraftPlugin/BuycraftPM#17]
I try the plugin in my pmmp server 1.2 alpha 9 bit and if I start my server the plugin won't load

**Comment by SnuffleeYT** [comment]
The plugin is only on Alpha8 so it won't work at 1.2 pocketmine :(

**Comment by liam-wiltshire** [comment]
We have merged a PR into master to support ALPHA9 and ALPHA10 - at the moment there isn't a downloadable phar for this, but if you build from master you should find it will work for you.
