### ISSUE TITLE
idk what this is

### ISSUE THREAD

**Issue by XoticRealmsOwnerandDev** [BuycraftPlugin/BuycraftPM#21]
15.12 13:14:20 [Server] Server thread/WARNING Unable to verify information
15.12 13:14:20 [Server] Server thread/CRITICAL Exception: "cURL request has failed: Resolving timed out after 5512 milliseconds" (EXCEPTION) in "BuycraftPM_v1.0.0.phar/src/Buycraft/PocketMine/PluginApi" at line 41
15.12 13:14:20 [Server] Server thread/DEBUG #0 BuycraftPM_v1.0.0.phar/src/Buycraft/PocketMine/BuycraftPlugin(72): Buycraft\PocketMine\PluginApi->basicGet(string /information)
15.12 13:14:20 [Server] Server thread/DEBUG #1 BuycraftPM_v1.0.0.phar/src/Buycraft/PocketMine/BuycraftPlugin(55): Buycraft\PocketMine\BuycraftPlugin->verifyInformation(Buycraft\PocketMine\PluginApi object)
15.12 13:14:20 [Server] Server thread/DEBUG #2 src/pocketmine/plugin/PluginBase(90): Buycraft\PocketMine\BuycraftPlugin->onEnable()
15.12 13:14:20 [Server] Server thread/DEBUG #3 src/pocketmine/plugin/PharPluginLoader(122): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
15.12 13:14:20 [Server] Server thread/DEBUG #4 src/pocketmine/plugin/PluginManager(610): pocketmine\plugin\PharPluginLoader->enablePlugin(Buycraft\PocketMine\BuycraftPlugin object)
15.12 13:14:20 [Server] Server thread/DEBUG #5 src/pocketmine/Server(1955): pocketmine\plugin\PluginManager->enablePlugin(Buycraft\PocketMine\BuycraftPlugin object)
15.12 13:14:20 [Server] Server thread/DEBUG #6 src/pocketmine/Server(1941): pocketmine\Server->enablePlugin(Buycraft\PocketMine\BuycraftPlugin object)
15.12 13:14:20 [Server] Server thread/DEBUG #7 src/pocketmine/Server(1735): pocketmine\Server->enablePlugins(integer 1)
15.12 13:14:20 [Server] Server thread/DEBUG #8 src/pocketmine/PocketMine(554): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
15.12 13:14:20 [Server] Server thread/DEBUG #9 /custom-php7.2.phar(1): require(string phar:///custom-php7.2.phar/src/pocketmine/PocketMine.php)

**Comment by liam-wiltshire** [comment]
This would suggest that your server was having problems resolving DNS lookups.

Hopefully this is working again now - if not, please contact Buycraft support (support@buycraft.net)
